fn to_usize(x: isize) usize {
    return @bitCast(x);
}

pub const errno_number = enum(u16) {
    _errno_success = 0,
    errno_perm = 1,
    errno_noent = 2,
    errno_srch = 3,
    errno_intr = 4,
    errno_io = 5,
    errno_nxio = 6,
    errno_2big = 7,
    errno_noexec = 8,
    errno_badf = 9,
    errno_child = 10,
    errno_again = 11,
    errno_nomem = 12,
    errno_acces = 13,
    errno_fault = 14,
    errno_notblk = 15,
    errno_busy = 16,
    errno_exist = 17,
    errno_xdev = 18,
    errno_nodev = 19,
    errno_notdir = 20,
    errno_isdir = 21,
    errno_inval = 22,
    errno_nfile = 23,
    errno_mfile = 24,
    errno_notty = 25,
    errno_txtbsy = 26,
    errno_fbig = 27,
    errno_nospc = 28,
    errno_spipe = 29,
    errno_rofs = 30,
    errno_mlink = 31,
    errno_pipe = 32,
    errno_dom = 33,
    errno_range = 34,
    errno_deadlk = 35,
    errno_nametoolong = 36,
    errno_nolck = 37,
    errno_nosys = 38,
    errno_notempty = 39,
    errno_loop = 40,
    errno_errno41 = 41,
    errno_nomsg = 42,
    errno_idrm = 43,
    errno_chrng = 44,
    errno_l2nsync = 45,
    errno_l3hlt = 46,
    errno_l3rst = 47,
    errno_lnrng = 48,
    errno_unatch = 49,
    errno_nocsi = 50,
    errno_l2hlt = 51,
    errno_bade = 52,
    errno_badr = 53,
    errno_xfull = 54,
    errno_noano = 55,
    errno_badrqc = 56,
    errno_badslt = 57,
    errno_errno58 = 58,
    errno_bfont = 59,
    errno_nostr = 60,
    errno_nodata = 61,
    errno_time = 62,
    errno_nosr = 63,
    errno_nonet = 64,
    errno_nopkg = 65,
    errno_remote = 66,
    errno_nolink = 67,
    errno_adv = 68,
    errno_srmnt = 69,
    errno_comm = 70,
    errno_proto = 71,
    errno_multihop = 72,
    errno_dotdot = 73,
    errno_badmsg = 74,
    errno_overflow = 75,
    errno_notuniq = 76,
    errno_badfd = 77,
    errno_remchg = 78,
    errno_libacc = 79,
    errno_libbad = 80,
    errno_libscn = 81,
    errno_libmax = 82,
    errno_libexec = 83,
    errno_ilseq = 84,
    errno_restart = 85,
    errno_strpipe = 86,
    errno_users = 87,
    errno_notsock = 88,
    errno_destaddrreq = 89,
    errno_msgsize = 90,
    errno_prototype = 91,
    errno_noprotoopt = 92,
    errno_protonosupport = 93,
    errno_socktnosupport = 94,
    errno_opnotsupp = 95,
    errno_pfnosupport = 96,
    errno_afnosupport = 97,
    errno_addrinuse = 98,
    errno_addrnotavail = 99,
    errno_netdown = 100,
    errno_netunreach = 101,
    errno_netreset = 102,
    errno_connaborted = 103,
    errno_connreset = 104,
    errno_nobufs = 105,
    errno_isconn = 106,
    errno_notconn = 107,
    errno_shutdown = 108,
    errno_toomanyrefs = 109,
    errno_timedout = 110,
    errno_connrefused = 111,
    errno_hostdown = 112,
    errno_hostunreach = 113,
    errno_already = 114,
    errno_inprogress = 115,
    errno_stale = 116,
    errno_uclean = 117,
    errno_notnam = 118,
    errno_navail = 119,
    errno_isnam = 120,
    errno_remoteio = 121,
    errno_dquot = 122,
    errno_nomedium = 123,
    errno_mediumtype = 124,
    errno_canceled = 125,
    errno_nokey = 126,
    errno_keyexpired = 127,
    errno_keyrevoked = 128,
    errno_keyrejected = 129,
    errno_ownerdead = 130,
    errno_notrecoverable = 131,
    errno_rfkill = 132,
    errno_hwpoison = 133,
    _errno_unknown = 134,
    _,
};

pub const errno = error{
    _errno_success,
    errno_perm,
    errno_noent,
    errno_srch,
    errno_intr,
    errno_io,
    errno_nxio,
    errno_2big,
    errno_noexec,
    errno_badf,
    errno_child,
    errno_again,
    errno_nomem,
    errno_acces,
    errno_fault,
    errno_notblk,
    errno_busy,
    errno_exist,
    errno_xdev,
    errno_nodev,
    errno_notdir,
    errno_isdir,
    errno_inval,
    errno_nfile,
    errno_mfile,
    errno_notty,
    errno_txtbsy,
    errno_fbig,
    errno_nospc,
    errno_spipe,
    errno_rofs,
    errno_mlink,
    errno_pipe,
    errno_dom,
    errno_range,
    errno_deadlk,
    errno_nametoolong,
    errno_nolck,
    errno_nosys,
    errno_notempty,
    errno_loop,
    errno_errno41,
    errno_nomsg,
    errno_idrm,
    errno_chrng,
    errno_l2nsync,
    errno_l3hlt,
    errno_l3rst,
    errno_lnrng,
    errno_unatch,
    errno_nocsi,
    errno_l2hlt,
    errno_bade,
    errno_badr,
    errno_xfull,
    errno_noano,
    errno_badrqc,
    errno_badslt,
    errno_errno58,
    errno_bfont,
    errno_nostr,
    errno_nodata,
    errno_time,
    errno_nosr,
    errno_nonet,
    errno_nopkg,
    errno_remote,
    errno_nolink,
    errno_adv,
    errno_srmnt,
    errno_comm,
    errno_proto,
    errno_multihop,
    errno_dotdot,
    errno_badmsg,
    errno_overflow,
    errno_notuniq,
    errno_badfd,
    errno_remchg,
    errno_libacc,
    errno_libbad,
    errno_libscn,
    errno_libmax,
    errno_libexec,
    errno_ilseq,
    errno_restart,
    errno_strpipe,
    errno_users,
    errno_notsock,
    errno_destaddrreq,
    errno_msgsize,
    errno_prototype,
    errno_noprotoopt,
    errno_protonosupport,
    errno_socktnosupport,
    errno_opnotsupp,
    errno_pfnosupport,
    errno_afnosupport,
    errno_addrinuse,
    errno_addrnotavail,
    errno_netdown,
    errno_netunreach,
    errno_netreset,
    errno_connaborted,
    errno_connreset,
    errno_nobufs,
    errno_isconn,
    errno_notconn,
    errno_shutdown,
    errno_toomanyrefs,
    errno_timedout,
    errno_connrefused,
    errno_hostdown,
    errno_hostunreach,
    errno_already,
    errno_inprogress,
    errno_stale,
    errno_uclean,
    errno_notnam,
    errno_navail,
    errno_isnam,
    errno_remoteio,
    errno_dquot,
    errno_nomedium,
    errno_mediumtype,
    errno_canceled,
    errno_nokey,
    errno_keyexpired,
    errno_keyrevoked,
    errno_keyrejected,
    errno_ownerdead,
    errno_notrecoverable,
    errno_rfkill,
    errno_hwpoison,
    _errno_unknown,
};

// inline to ensure fast success
pub inline fn chkerr(rc: usize) errno!usize {
    if (rc >= to_usize(-4095)) {
        @branchHint(.unlikely);
        const err_val: u16 = @intCast(-@as(isize, @bitCast(rc)));
        const adj_err = err_val + @intFromError(errno._errno_success);
        if (adj_err >= @intFromError(errno._errno_unknown)) return errno._errno_unknown;
        return @errorCast(@errorFromInt(adj_err));
    }
    return rc;
}

const std = @import("std");
const tt = std.testing;

test {
    try tt.expectEqual(@as(usize, 0), chkerr(0));
    try tt.expectEqual(to_usize(-4096), chkerr(to_usize(-4096)));
    try tt.expectError(errno._errno_unknown, chkerr(to_usize(-4095)));
    try tt.expectError(errno.errno_perm, chkerr(to_usize(-1)));
    try tt.expectError(errno.errno_errno41, chkerr(to_usize(-41)));
}
